# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 14:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('por', '0003_auto_20170108_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='grade',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='car',
            name='rotation_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
